name: module_b
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^5.1.0

flutter:
